### ISSUE TITLE
correct usage of reduce-reducers

### ISSUE THREAD

**Issue by zatziky** [redux-utilities/reduce-reducers#5] opened 2016-07-29 12:32 UTC
Hi, 

am I correct on the usage of this lib? I kind of don't get. Please have a look at 
http://stackoverflow.com/questions/38652789/correct-usage-of-reduce-reducers/38658551#38658551

Zat

**Comment by tricoder42** [comment] 2017-07-02 15:14
Probably duplicate of #8

**Comment by timche** [comment] 2018-04-13 10:26
Answered by @tricoder42.

**Closed by timche** 2018-04-13 10:26 UTC
